export const translations = {
  en: {
    header: {
      aboutMe: 'ABOUT_ME',
      skills: 'SKILLS',
      experience: 'EXPERIENCE',
      projects: 'PROJECTS',
      education: 'EDUCATION',
      contact: 'CONTACT',
      linkedin: 'LINKEDIN'
    },
    hero: {
      subtitle: '// Hello, welcome!',
      role: 'SENIOR FULLSTACK DEVELOPER',
      description: 'With a career dedicated to developing technological solutions, I am part of the CAST team as a Senior Fullstack Developer, specializing in all typescript frameworks. My role is vital in the Technical Debt and at a project known as QTeste of client company, where we improve test management, significantly contributing to the institution\'s operational efficiency.',
      techStackTitle: '## Main Technologies',
      codeComment: '// developer.config.ts',
      codeName: 'Edvaldo Junior',
      codeLocation: 'Sorocaba, SP - Brazil',
      codeExperience: '+10 years',
      codeStatus: 'working'
    },
    stats: {
      experienceLabel: 'EXPERIENCE >',
      experienceValue: '+10 YEARS',
      projectsLabel: 'PROJECTS >',
      projectsValue: '+10',
      levelLabel: 'LEVEL >',
      levelValue: 'SENIOR',
      locationLabel: 'LOCATION >',
      locationValue: 'SOROCABA, SP - BRAZIL',
      ctaButton: 'async () => contact(email)'
    },
    skills: {
      title: 'SKILLS',
      frontend: 'Frontend',
      backend: 'Backend',
      database: 'Database',
      devops: 'DevOps',
      aiml: 'AI/ML',
      microservices: 'Microservices'
    },
    experience: {
      title: 'experience',
      castRole: 'Senior Fullstack Developer (Angular and NodeJS)',
      castPeriod: 'May 2022 - Present',
      castLocation: 'Home office',
      castDescription: 'I worked on two strategic fronts of software engineering. As a developer on the QTeste project, I worked on an internal platform for test automation and evidence generation. Simultaneously, in the Technical Debt team, I worked on mapping and analyzing technical debt across multiple projects, helping to direct quality improvements and code sustainability to optimize client company\'s systems.',
      
      revaloRole: 'AI Trainer',
      revaloPeriod: 'May 2025 - June 2025',
      revaloLocation: 'Home office',
      revaloDescription: 'Support for one of the human-generated data projects. In this role, I help improve the performance of a large language model by solving programming challenges and evaluating solutions and prompts generated by artificial intelligence.',
      
      infosysRole: 'Senior Backend Developer (NodeJS)',
      infosysPeriod: 'May 2021 - May 2022',
      infosysLocation: 'Home office',
      infosysDescription: 'I worked in the backend team on a client venture called Loadshark, a cargo and freight management platform.',
      
      farmaPonteRole: 'Senior Fullstack Developer (ReactJS)',
      farmaPontePeriod: 'November 2020 - May 2021',
      farmaPonteLocation: 'Sorocaba, SP',
      farmaPonteDescription: 'I worked on the company\'s legacy systems and also on database query and update routines using SQL Server.',
      
      grupoSolucoesRole: 'Junior Frontend Developer',
      grupoSolucoesPeriod: 'May 2020 - November 2020',
      grupoSolucoesLocation: 'Sorocaba, SP',
      grupoSolucoesDescription: 'I worked on creating promotional materials for the company\'s social media and also developed landing pages for specific special promotions.',
      
      greenoneRole: 'Junior Frontend Developer',
      greenonePeriod: 'January 2019 - April 2020',
      greenoneLocation: 'Votorantim, SP',
      greenoneDescription: 'I worked on maintenance and management of various client pages and systems.',
      
      capgeminiRole: 'Junior Infrastructure Technician',
      capgeminiPeriod: 'April 2013 - January 2015',
      capgeminiLocation: 'Votorantim, SP',
      capgeminiDescription: 'I was responsible for the IT department. I assisted in the use, maintenance, configuration and repair of the entire IT infrastructure, including thin clients, desktops and notebooks.',
      
      year: 'year',
      years: 'years',
      month: 'month',
      months: 'months'
    },
    projects: {
      title: 'projects',
      website: 'website',
      github: 'github',
      npm: 'npm',
      easyChatDescription: 'The secure, plug-and-play AI Chat Widget for React. Add a ChatGPT-powered assistant to your application in seconds, without exposing your API Keys.',
      discordiaDescription: 'A contentious chat between the leading AIs on the market, competing for the best answer to your questions! A digital arena where multiple AIs compete in real time.',
      formaiDescription: 'Generate form fields and validations (React, Vue, Angular) from natural language prompts. Stop wasting time hunting for validation regex or manually building complex validation logic.',
      comingSoon: 'coming soon...'
    },
    education: {
      title: 'education',
      unip: 'UNIP - Paulista University',
      unipDegree: 'Bachelor\'s Degree in Computer Systems Analysis',
      unipPeriod: 'January 2026 - January 2028',
      etec: 'ETEC - State Technical School of São Paulo',
      etecDegree: 'Technical Education in Information Technology/Software',
      etecPeriod: '2010 - 2011'
    },
    certifications: {
      title: 'certifications',
      googleCoding: 'Google Coding Fundamentals',
      efset: 'EF SET English',
      efsetScore: '65/100 - C1 Effective Proficiency'
    },
    contact: {
      title: 'contact',
      email: 'EMAIL',
      phone: 'PHONE',
      linkedin: 'LINKEDIN',
      location: 'LOCATION',
      locationValue: 'Sorocaba, São Paulo, Brazil'
    }
  },
  pt: {
    header: {
      aboutMe: 'SOBRE_MIM',
      skills: 'HABILIDADES',
      experience: 'EXPERIÊNCIA',
      projects: 'PROJETOS',
      education: 'FORMAÇÃO',
      contact: 'CONTATO',
      linkedin: 'LINKEDIN'
    },
    hero: {
      subtitle: '// Olá, seja bem-vindo!',
      role: 'DESENVOLVEDOR FULLSTACK SÊNIOR',
      description: 'Com uma carreira dedicada ao desenvolvimento de soluções tecnológicas, faço parte da equipe da CAST como Desenvolvedor Fullstack Sênior, especializado em todos os frameworks typescript. Meu papel é vital na Dívida Técnica e em um projeto conhecido como QTeste da empresa cliente, onde melhoramos a gestão de testes, contribuindo significativamente para a eficiência operacional da instituição.',
      techStackTitle: '## Principais Tecnologias',
      codeComment: '// desenvolvedor.config.ts',
      codeName: 'Edvaldo Junior',
      codeLocation: 'Sorocaba, SP - Brasil',
      codeExperience: '+10 anos',
      codeStatus: 'trabalhando'
    },
    stats: {
      experienceLabel: 'EXPERIÊNCIA >',
      experienceValue: '+10 ANOS',
      projectsLabel: 'PROJETOS >',
      projectsValue: '+10',
      levelLabel: 'NÍVEL >',
      levelValue: 'SÊNIOR',
      locationLabel: 'LOCALIZAÇÃO >',
      locationValue: 'SOROCABA, SP - BRASIL',
      ctaButton: 'async () => contato(email)'
    },
    skills: {
      title: 'HABILIDADES',
      frontend: 'Frontend',
      backend: 'Backend',
      database: 'Banco de Dados',
      devops: 'DevOps',
      aiml: 'IA/ML',
      microservices: 'Microsserviços'
    },
    experience: {
      title: 'experiência',
      castRole: 'Desenvolvedor Fullstack Sênior (Angular e NodeJS)',
      castPeriod: 'Mai 2022 - Presente',
      castLocation: 'Home office',
      castDescription: 'Atuei em duas frentes estratégicas de engenharia de software. Como desenvolvedor no projeto QTeste, trabalhei em uma plataforma interna para automação de testes e geração de evidências. Simultaneamente, na equipe de Dívida Técnica, atuei no mapeamento e análise de débitos técnicos em múltiplos projetos, ajudando a direcionar melhorias de qualidade e sustentabilidade do código para otimizar os sistemas da empresa cliente.',
      
      revaloRole: 'Treinador de IA',
      revaloPeriod: 'Mai 2025 - Jun 2025',
      revaloLocation: 'Home office',
      revaloDescription: 'Suporte para um dos projetos de dados gerados por humanos. Nesta função, ajudo a melhorar o desempenho de um modelo de linguagem grande, resolvendo desafios de programação e avaliando soluções e prompts gerados por inteligência artificial.',
      
      infosysRole: 'Desenvolvedor Backend Sênior (NodeJS)',
      infosysPeriod: 'Mai 2021 - Mai 2022',
      infosysLocation: 'Home office',
      infosysDescription: 'Atuei na equipe de backend em um empreendimento de cliente chamado Loadshark, uma plataforma de gestão de carga e frete.',
      
      farmaPonteRole: 'Desenvolvedor Fullstack Sênior (ReactJS)',
      farmaPontePeriod: 'Nov 2020 - Mai 2021',
      farmaPonteLocation: 'Sorocaba, SP',
      farmaPonteDescription: 'Trabalhei nos sistemas legados da empresa e também em rotinas de consulta e atualização de banco de dados usando SQL Server.',
      
      grupoSolucoesRole: 'Desenvolvedor Frontend Júnior',
      grupoSolucoesPeriod: 'Mai 2020 - Nov 2020',
      grupoSolucoesLocation: 'Sorocaba, SP',
      grupoSolucoesDescription: 'Trabalhei na criação de materiais promocionais para as redes sociais da empresa e também desenvolvi landing pages para promoções especiais específicas.',
      
      greenoneRole: 'Desenvolvedor Frontend Júnior',
      greenonePeriod: 'Jan 2019 - Abr 2020',
      greenoneLocation: 'Votorantim, SP',
      greenoneDescription: 'Trabalhei na manutenção e gestão de várias páginas e sistemas de clientes.',
      
      capgeminiRole: 'Técnico de Infraestrutura Júnior',
      capgeminiPeriod: 'Abr 2013 - Jan 2015',
      capgeminiLocation: 'Votorantim, SP',
      capgeminiDescription: 'Fui responsável pelo departamento de TI. Auxiliei no uso, manutenção, configuração e reparo de toda a infraestrutura de TI, incluindo thin clients, desktops e notebooks.',
      
      year: 'ano',
      years: 'anos',
      month: 'mês',
      months: 'meses'
    },
    projects: {
      title: 'projetos',
      website: 'site',
      github: 'github',
      npm: 'npm',
      easyChatDescription: 'O Widget de Chat IA seguro e plug-and-play para React. Adicione um assistente baseado em ChatGPT à sua aplicação em segundos, sem expor suas chaves de API.',
      discordiaDescription: 'Um chat contencioso entre as principais IAs do mercado, competindo pela melhor resposta às suas perguntas! Uma arena digital onde múltiplas IAs competem em tempo real.',
      formaiDescription: 'Gere campos de formulário e validações (React, Vue, Angular) a partir de prompts em linguagem natural. Pare de perder tempo procurando regex de validação ou construindo manualmente lógica de validação complexa.',
      comingSoon: 'em breve...'
    },
    education: {
      title: 'formação',
      unip: 'UNIP - Universidade Paulista',
      unipDegree: 'Bacharelado em Análise de Sistemas de Computador',
      unipPeriod: 'Janeiro 2026 - Janeiro 2028',
      etec: 'ETEC - Escola Técnica Estadual de São Paulo',
      etecDegree: 'Educação Técnica em Tecnologia da Informação/Software',
      etecPeriod: '2010 - 2011'
    },
    certifications: {
      title: 'certificações',
      googleCoding: 'Google Fundamentos de Codificação',
      efset: 'EF SET Inglês',
      efsetScore: '65/100 - C1 Proficiência Efetiva'
    },
    contact: {
      title: 'contato',
      email: 'EMAIL',
      phone: 'TELEFONE',
      linkedin: 'LINKEDIN',
      location: 'LOCALIZAÇÃO',
      locationValue: 'Sorocaba, São Paulo, Brasil'
    }
  }
}
