import { useState } from 'react'
import { 
  Clock, 
  MapPin, 
  Mail, 
  Phone, 
  Linkedin, 
  ScrollText, 
  Globe, 
  ExternalLink 
} from 'lucide-react'
import DiscordiaImg  from './assets/discordia-preview.png'
import EasyChatImg from './assets/easychat-preview.png'
import './App.css'

function App() {
  const [menuOpen, setMenuOpen] = useState(false)

  const toggleMenu = () => {
    setMenuOpen(!menuOpen)
  }

  const closeMenu = () => {
    setMenuOpen(false)
  }

  const handleNavClick = (e: React.MouseEvent<HTMLElement>, targetId: string) => {
    e.preventDefault()
    closeMenu()
    
    // Pequeno delay para garantir que o menu feche antes do scroll
    setTimeout(() => {
      const element = document.getElementById(targetId)
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' })
      }
    }, 100)
  }

  const calculateDuration = (startMonth: number, startYear: number, endMonth?: number, endYear?: number) => {
    const startDate = new Date(startYear, startMonth)
    const endDate = endYear !== undefined && endMonth !== undefined ? new Date(endYear, endMonth) : new Date()
    
    let years = endDate.getFullYear() - startDate.getFullYear()
    let months = endDate.getMonth() - startDate.getMonth()

    if (months < 0) {
      years--
      months += 12
    }

    let durationStr = ''
    if (years > 0) {
      durationStr += `${years} year${years > 1 ? 's' : ''} `
    }
    if (months > 0) {
      durationStr += `${months} month${months > 1 ? 's' : ''}`
    }

    return durationStr.trim()
  }

  const experiences = [
    {
      company: "CAST",
      role: "Senior Fullstack Developer (Angular and NodeJS)",
      period: "May 2022 - Present",
      duration: calculateDuration(3, 2022),
      location: "Home office",
      description: "I worked on two strategic fronts of software engineering. As a developer on the QTeste project, I worked on an internal platform for test automation and evidence generation. Simultaneously, in the Technical Debt team, I worked on mapping and analyzing technical debt across multiple projects, helping to direct quality improvements and code sustainability to optimize Banco do Brasil's systems.",
      startMonth: 3,
      startYear: 2022,
    },
    {
      company: "Revelo",
      role: "AI Trainer",
      period: "May 2025 - June 2025",
      duration: calculateDuration(4, 2025, 5, 2025),
      location: "Home office",
      description: "Support for one of the human-generated data projects. In this role, I help improve the performance of a large language model by solving programming challenges and evaluating solutions and prompts generated by artificial intelligence.",
      startMonth: 4,
      startYear: 2025,
      endMonth: 5,
      endYear: 2025,
    },
    {
      company: "Infosys",
      role: "Senior Backend Developer (NodeJS)",
      period: "May 2021 - May 2022",
      duration: calculateDuration(4, 2021, 4, 2022),
      location: "Home office",
      description: "I worked in the backend team on a client venture called Loadshark, a cargo and freight management platform.",
      startMonth: 4,
      startYear: 2021,
      endMonth: 4,
      endYear: 2022,
    },
    {
      company: "Farma Ponte",
      role: "Senior Fullstack Developer (ReactJS)",
      period: "November 2020 - May 2021",
      duration: calculateDuration(10, 2020, 4, 2021),
      location: "Sorocaba, SP",
      description: "I worked on the company's legacy systems and also on database query and update routines using SQL Server.",
      startMonth: 10,
      startYear: 2020,
      endMonth: 4,
      endYear: 2021,
    },
    {
      company: "Grupo Soluções",
      role: "Junior Frontend Developer",
      period: "May 2020 - November 2020",
      duration: calculateDuration(4, 2020, 10, 2020),
      location: "Sorocaba, SP",
      description: "I worked on creating promotional materials for the company's social media and also developed landing pages for specific special promotions.",
      startMonth: 4,
      startYear: 2020,
      endMonth: 10,
      endYear: 2020,
    },
    {
      company: "Greenone Proximity Technology",
      role: "Junior Frontend Developer",
      period: "January 2019 - April 2020",
      duration: calculateDuration(0, 2019, 3, 2020),
      location: "Votorantim, SP",
      description: "I worked on maintenance and management of various client pages and systems.",
      startMonth: 0,
      startYear: 2019,
      endMonth: 3,
      endYear: 2020,
    },
    {
      company: "Capgemini",
      role: "Junior Infrastructure Technician",
      period: "April 2013 - January 2015",
      duration: calculateDuration(3, 2013, 0, 2015),
      location: "Votorantim, SP",
      description: "I was responsible for the IT department. I assisted in the use, maintenance, configuration and repair of the entire IT infrastructure, including thin clients, desktops and notebooks.",
      startMonth: 3,
      startYear: 2013,
      endMonth: 0,
      endYear: 2015,
    }
  ];

  const skills = [
    { category: "Frontend", items: ["React", "Angular", "Next.js", "TypeScript"] },
    { category: "Backend", items: ["Node.js", "Nest.js", "Express.js", "REST APIs"] },
    { category: "Database", items: ["PostgreSQL", "MongoDB", "MySQL", "OracleDB", "SQL Server"] },
    { category: "DevOps", items: ["Docker", "Kubernetes", "AWS", "OpenShift", "Linux"] },
    { category: "AI/ML", items: ["LLM", "MCP", "Prompt Engineering"] },
    { category: "Microservices", items: ["Microserviços", "API Gateway", "Message Queue"] }
  ];

  const education = [
    {
      institution: "UNIP - Paulista University",
      degree: "Bachelor's Degree in Computer Systems Analysis",
      period: "January 2026 - January 2028"
    },
    {
      institution: "ETEC - State Technical School of São Paulo",
      degree: "Technical Education in Information Technology/Software",
      period: "2010 - 2011"
    }
  ];

  return (
    <div className="app">
      {/* Header - Desktop View */}
      <header className="desktop-header">
        <div className="logo" onClick={(e) => handleNavClick(e, 'about')}>
          &lt;e<span className="highlight">95</span>/&gt;
        </div>

        <nav className="nav">
          <a href="#about" onClick={(e) => handleNavClick(e, 'about')}>ABOUT ME</a>
          <a href="#skills" onClick={(e) => handleNavClick(e, 'skills')}>SKILLS</a>
          <a href="#experience" onClick={(e) => handleNavClick(e, 'experience')}>EXPERIENCE</a>
          <a href="#projects" onClick={(e) => handleNavClick(e, 'projects')}>PROJECTS</a>
          <a href="#education" onClick={(e) => handleNavClick(e, 'education')}>EDUCATION</a>
          <a href="#contact" onClick={(e) => handleNavClick(e, 'contact')}>CONTACT</a>
        </nav>

        <div className="header-actions">
          <a href="https://www.linkedin.com/in/deved-jr100" target="_blank" rel="noopener noreferrer" className="enroll-btn">
            {'()'} =&gt; {'{ '+ 'LINKEDIN' + ' }'}
          </a>
        </div>
      </header>

      {/* Header - Mobile View */}
      <header className="mobile-header">
        <div className="logo" onClick={(e) => handleNavClick(e, 'about')}>
          &lt;e<span className="highlight">95</span>/&gt;
        </div>
        
        {/* Hamburger Button */}
        <button 
          className={`hamburger ${menuOpen ? 'active' : ''}`} 
          onClick={toggleMenu}
          aria-label="Toggle menu"
        >
          <span className="hamburger-line"></span>
          <span className="hamburger-line"></span>
          <span className="hamburger-line"></span>
        </button>

        <nav className={`nav ${menuOpen ? 'nav-open' : ''}`}>
          <a href="#about" onClick={(e) => handleNavClick(e, 'about')}>ABOUT ME</a>
          <a href="#skills" onClick={(e) => handleNavClick(e, 'skills')}>SKILLS</a>
          <a href="#experience" onClick={(e) => handleNavClick(e, 'experience')}>EXPERIENCE</a>
          <a href="#projects" onClick={(e) => handleNavClick(e, 'projects')}>PROJECTS</a>
          <a href="#education" onClick={(e) => handleNavClick(e, 'education')}>EDUCATION</a>
          <a href="#contact" onClick={(e) => handleNavClick(e, 'contact')}>CONTACT</a>
        <div className="header-actions">
          <a href="https://www.linkedin.com/in/deved-jr100" target="_blank" rel="noopener noreferrer" className="enroll-btn">
            {'()'} =&gt; {'{ '+ 'LINKEDIN' + ' }'}
          </a>
        </div>
        </nav>
      </header>
    
      {/* Hero Section */}
      <main className="main">
        <section id="about" className="hero">
          <div className="hero-content">
            <p className="hero-subtitle">// Hello, welcome!</p>
            <h1 className="hero-title">Edvaldo Ramos <span className="highlight">Junior</span></h1>
            <p className="hero-role">SENIOR FULLSTACK DEVELOPER</p>
            <p className="hero-description">
              With a career dedicated to developing technological solutions, 
              I am part of the CAST team as a Senior Fullstack Developer, 
              specializing in all typescript frameworks. My role is vital in the Technical Debt and QTeste project 
              at Banco do Brasil, where we improve test management, 
              significantly contributing to the institution's operational efficiency.
            </p>
          </div>
          
          <div className="hero-visual">
            <div className="code-block">
              <span className="code-comment">{"// developer.config.ts"}</span>
              <br />
              <span className="code-keyword">const</span> <span className="code-var">greatDeveloper</span> = {"{"}
              <br />
              <span className="code-prop">  name:</span> <span className="code-string">"Edvaldo Junior"</span>,
              <br />
              <span className="code-prop">  location:</span> <span className="code-string">"Sorocaba, SP - Brazil"</span>,
              <br />
              <span className="code-prop">  experience:</span> + <span className="code-number">10</span> years,
              <br />
              <span className="code-prop">  status:</span> <span className="code-string">"working"</span>
              <br />
              {"}"};
            </div>
          </div>
        </section>

        {/* Stats Info */}
        <section className="course-info">
          <div className="info-stats">
            <div className="stat">
              <span className="stat-label">EXPERIENCE &gt;</span>
              <span className="stat-value highlight">+10 YEARS</span>
            </div>
            <div className="stat">
              <span className="stat-label">PROJECTS &gt;</span>
              <span className="stat-value highlight">+10</span>
            </div>
            <div className="stat">
              <span className="stat-label">LEVEL &gt;</span>
              <span className="stat-value highlight">SENIOR</span>
            </div>
            <div className="stat">
              <span className="stat-label">LOCATION &gt;</span>
              <span className="stat-value highlight">SOROCABA, SP - BRAZIL</span>
            </div>
          </div>
          <a href="mailto:e.junior95@gmail.com" className="cta-btn">async () =&gt; contact(email)</a>
        </section>

        {/* Skills Section */}
        <section id="skills" className="section">
          <h2 className="section-title">
            <span className="code-bracket">{"{"}</span> SKILLS <span className="code-bracket">{"}"}</span>
          </h2>
          <div className="skills-grid">
            {skills.map((skillGroup, index) => (
              <div key={index} className="skill-card">
                <span className="skill-category">// {skillGroup.category}</span>
                <div className="skill-items">
                  {skillGroup.items.map((item, i) => (
                    <span key={i} className="skill-tag">{item}</span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Experience Section */}
        <section id="experience" className="section">
          <h2 className="section-title">
            <span className="code-bracket">{"["}</span> experience <span className="code-bracket">{"]"}</span>
          </h2>
          <div className="timeline">
            {experiences.map((exp, index) => (
              <div key={index} className="timeline-item">
                <div className="timeline-marker">
                  <span className="timeline-index">{(experiences.length - index) - 1}</span>
                </div>
                <div className="timeline-content">
                  <div className="timeline-header">
                    <h3 className="company-name">{exp.company}</h3>
                    <span className="timeline-period">{exp.period}</span>
                  </div>
                  <p className="role-title">{exp.role}</p>
                  <div className="timeline-meta">
                    <span className="meta-item"><Clock size={16} style={{ marginRight: '4px' }} /> {exp.duration}</span>
                    <span className="meta-item"><MapPin size={16} style={{ marginRight: '4px' }} /> {exp.location}</span>
                  </div>
                  <p className="timeline-description">{exp.description}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Projects Section */}
        <section id="projects" className="section">
          <h2 className="section-title">
            <span className="code-bracket">{"@"}</span> projects
          </h2>
          <div className="projects-grid">
            {/* FormAI Project */}
            <div className="project-card">
              <div className="project-header">
                <h3 className="project-title">FormAI</h3>
                <div className="project-links">
                  <a href="https://github.com/ejunior95/formai" target="_blank" rel="noopener noreferrer" className="project-link">
                    <span>github</span>
                    <ExternalLink size={14} />
                  </a>
                  <a href="https://www.npmjs.com/package/@ejunior95/formai-core" target="_blank" rel="noopener noreferrer" className="project-link">
                    <span>npm</span>
                    <ExternalLink size={14} />
                  </a>
                </div>
              </div>
              <p className="project-description">
                Generate form fields and validations (React, Vue, Angular) from natural language prompts. 
                Stop wasting time hunting for validation regex or manually building complex validation logic.
              </p>
              <div className="project-tech">
                <span className="tech-tag">React</span>
                <span className="tech-tag">Vue</span>
                <span className="tech-tag">Angular</span>
                <span className="tech-tag">TypeScript</span>
                <span className="tech-tag">AI</span>
              </div>
              <div className="project-preview">
                <div className="crt-monitor">
                  <div className="crt-screen">
                    <div className="crt-content">
                      {/* Espaço reservado para screenshot do FormAI */}
                      <div className="screenshot-placeholder">
                        <span>// FormAI Screenshot</span>
                        <span>coming soon...</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* EasyChat Project */}
            <div className="project-card">
              <div className="project-header">
                <h3 className="project-title">EasyChat</h3>
                <div className="project-links">
                  <a href="https://easychat.ia.br/" target="_blank" rel="noopener noreferrer" className="project-link">
                    <span>website</span>
                    <ExternalLink size={14} />
                  </a>
                  <a href="https://github.com/ejunior95/easychat-landing-page" target="_blank" rel="noopener noreferrer" className="project-link">
                    <span>github</span>
                    <ExternalLink size={14} />
                  </a>
                  <a href="https://www.npmjs.com/package/@ejunior95/easy-chat" target="_blank" rel="noopener noreferrer" className="project-link">
                    <span>npm</span>
                    <ExternalLink size={14} />
                  </a>
                </div>
              </div>
              <p className="project-description">
                The secure, plug-and-play AI Chat Widget for React. Add a ChatGPT-powered assistant to your 
                application in seconds, without exposing your API Keys.
              </p>
              <div className="project-tech">
                <span className="tech-tag">React</span>
                <span className="tech-tag">TypeScript</span>
                <span className="tech-tag">OpenAI</span>
                <span className="tech-tag">Security</span>
              </div>
              <div className="project-preview">
                <div className="crt-monitor">
                  <div className="crt-screen">
                    <div className="crt-content">
                      <img className="project-screenshot" src={EasyChatImg} alt="EasyChat Screenshot" />
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* DiscordIA Project */}
            <div className="project-card">
              <div className="project-header">
                <h3 className="project-title">DiscordIA</h3>
                <div className="project-links">
                  <a href="https://discordia.app.br/" target="_blank" rel="noopener noreferrer" className="project-link">
                    <span>website</span>
                    <ExternalLink size={14} />
                  </a>
                  <a href="https://github.com/ejunior95/discordia" target="_blank" rel="noopener noreferrer" className="project-link">
                    <span>github</span>
                    <ExternalLink size={14} />
                  </a>
                </div>
              </div>
              <p className="project-description">
                Um chat conflituoso entre as principais IAs do mercado, disputando pela melhor resposta para suas perguntas! 
                Uma arena digital onde múltiplas IAs competem em tempo real.
              </p>
              <div className="project-tech">
                <span className="tech-tag">NestJS</span>
                <span className="tech-tag">OpenAI</span>
                <span className="tech-tag">Gemini</span>
                <span className="tech-tag">DeepSeek</span>
                <span className="tech-tag">AI</span>
              </div>
              <div className="project-preview">
                <div className="crt-monitor">
                  <div className="crt-screen">
                    <div className="crt-content">
                      <img className="project-screenshot" src={DiscordiaImg} alt="DiscordIA Screenshot" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* Education Section */}
        <section id="education" className="section">
          <h2 className="section-title">
            <span className="code-bracket">{"<"}</span> education <span className="code-bracket">{"/>"}</span>
          </h2>
          <div className="education-grid">
            {education.map((edu, index) => (
              <div key={index} className="education-card">
                {/* <span className="edu-index">0{index + 1}</span> */}
                <h3 className="edu-institution">{edu.institution}</h3>
                <p className="edu-degree">{edu.degree}</p>
                <span className="edu-period">{edu.period}</span>
              </div>
            ))}
          </div>
        </section>

        {/* Certifications Section */}
        <section className="section">
          <h2 className="section-title">
            <span className="code-bracket">{"/*"}</span> certifications <span className="code-bracket">{"*/"}</span>
          </h2>
          <div className="certifications-grid">
            <div className="cert-card">
              <span className="cert-icon"><ScrollText size={28} /></span>
              <h4 className="cert-name">Google Coding Fundamentals</h4>
            </div>
            <div className="cert-card">
              <span className="cert-icon"><Globe size={28} /></span>
              <h4 className="cert-name">EF SET English</h4>
              <p className="cert-score">65/100 - C1 Effective Proficiency</p>
            </div>
          </div>
        </section>

        {/* Contact Section */}
        <section id="contact" className="section contact-section">
          <h2 className="section-title">
            <span className="code-bracket">{"("}</span> contact <span className="code-bracket">{")"}</span>
          </h2>
          <div className="contact-grid">
            <a href="mailto:e.junior95@gmail.com" className="contact-card">
              <span className="contact-icon"><Mail size={28} /></span>
              <span className="contact-label">EMAIL</span>
              <span className="contact-value">e.junior95@gmail.com</span>
              <ExternalLink size={16} style={{ marginLeft: '4px', opacity: 0.6 }} />
            </a>
            <a href="tel:+5515988309658" className="contact-card">
              <span className="contact-icon"><Phone size={28} /></span>
              <span className="contact-label">PHONE</span>
              <span className="contact-value">+ 55 (15) 98830-9658</span>
            </a>
            <a href="https://www.linkedin.com/in/deved-jr100" target="_blank" rel="noopener noreferrer" className="contact-card">
              <span className="contact-icon"><Linkedin size={28} /></span>
              <span className="contact-label">LINKEDIN</span>
              <span className="contact-value">linkedin.com/in/deved-jr100</span>
              <ExternalLink size={16} style={{ marginLeft: '4px', opacity: 0.6 }} />
            </a>
            <div className="contact-card">
              <span className="contact-icon"><MapPin size={28} /></span>
              <span className="contact-label">LOCATION</span>
              <span className="contact-value">Sorocaba, São Paulo, Brazil</span>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="footer">
          <p className="footer-text">
            &lt;ejunior95 /&gt; © {new Date().getFullYear()}
          </p>
        </footer>
      </main>
    </div>
  )
}

export default App
